### ISSUE TITLE
Unable to use MQTT in & out nodes in Node-Red

### ISSUE THREAD

**Issue by jerome83136** [linto-ai/linto-skills-components#4]
Hello,

When I try to use the mqtt-in or mqtt-out nodes on Node-Red, the broker configuration disapears after clicking on "save and publish".

I've noticed these errors in the following container: 

docker logs linto_stack_linto-platform-bls.1.1kfqmnyz42erdfo3gpoy66b4n

```
24 Mar 21:51:46 - [error] [linto-ui:d6ab5be6-8cd1-11eb-905a-05a18197af9b] TypeError: Cannot read property 'config' of null
24 Mar 21:51:46 - [info] Updated flow: testApp1 [722cfb5.12a4304]
```

And the mqtt node appears with a red dot on Node-Red, saying it misses the broker config.

I did the broker configuration several times (configured host/port/login/password), but it seems the configuration is erased after clicking on "save and publish"

Did I miss something ?

Thank you for your help

Best regards

PS: not sure I have posted this issue on the right Git repo. Please say me if I should create it anywhere else.

**Comment by Houpert** [comment]
Hello,

The configuration linto-config node is erased by linto-admin to setup the server settings for each save & pulish.

Regarding the error it's on linto-ui node, it's a WIP feature that we have put in stand by, you can just remove the linto-ui node in the sandbox / workflow and you will not see that error again.

Regarding the red dot, it's maybe related to you'r settings (.dockerenv). Did you have try to make any call with a LinTO to see if the workflow is working ?

Best regards

**Comment by jerome83136** [comment]
Hello,

I think I didn't explain clearly enough what I'm trying to do.

I would like to use the mqtt in & out nodes to communicate with an arbitrary mqtt instance (not the linto central mqtt instance)
So I think I can't use the linto-config node because it stores only the linto central mqtt settings. (It can't be aware of my custom external mqtt instance)

To summarize: are mqtt in & out nodes able to talk to an external arbitrary mqtt instance ?

Thank you for your help
Best regards

**Comment by damienlaine** [comment]
The LinTO Workflows are supposed to work with "skills" that are connected to events fired on intentions being spotted.

I'll suggest you to investigate that. Nothing prevents you from building a custom "Home Assistant Light control skill for LinTO" that would :
- Bounce to some specific voice commands
- Forward specific commands to Home Assistant through a standard Node-Red MQTT node or any kind of API. Or even wire-out to node-red defined set of actions

You should implement your command / answers in the skill itself

The LinTO Skill template and provided examples for quickly writing your own skills are really easy to understand. But i suggest that you step into this.

Check docs : https://doc.linto.ai/#/skills/devguide/make_my_skills and read the code for the provided example skills, they are easy to understand / hack and install.

**Comment by jerome83136** [comment]
Hello,

Thank you for your answer.
I'll give it a look and see how I can manage this.

I'll keep progress on this issue so that other people could benefit my examples and progress.

I'll choose the issue as soon as I will get a working solution.

Best regards
